name: Build and release

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
    tags: ["v*.*.*"]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_release:
    runs-on: ${{ matrix.job.os }}
    strategy:
      matrix:
        job:
        - os: ubuntu-latest
          target: x86_64-unknown-linux-gnu
        - os: macos-latest
          target: aarch64-apple-darwin
#        - os: windows-latest
#          target: x86_64-pc-windows-gnu
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Build Wasm
      run: |
        dotnet workload install wasm-tools -v detailed
        dotnet publish RmqToolsWeb/RmqToolsWeb/RmqToolsWeb.csproj -c Release --output wasm_out

    - name: "Caching cargo & rustup"
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          ~/.rustup
          target
        key: ${{ runner.os }}

    - name: install target
      run: |
        rustup target add ${{ matrix.job.target }}
        rustup show

    - name: Build
      run: cargo build --release --verbose --target=${{ matrix.job.target }}

    - name: Create zip file
      id: bin
      shell: bash
      run: |
        # Figure out suffix of binary
        EXE_suffix=""
        case ${{ matrix.job.target }} in
          *-pc-windows-*) EXE_suffix=".exe" ;;
        esac;
        
        APP_NAME="rmq-tools"
        
        # Setup paths
        mkdir -p out
        BIN_PATH="target/${{ matrix.job.target }}/release/${APP_NAME}${EXE_suffix}"
        ARTIFACT_PATH="${{ github.workspace }}/out/${APP_NAME}-${{github.ref_name}}-${{ matrix.job.target }}${EXE_suffix}"
        
        cp $BIN_PATH $ARTIFACT_PATH
        cp wasm_out/wwwroot out/

        ARCHIVE_PATH="${{ github.workspace }}/${APP_NAME}-${{github.ref_name}}-${{ matrix.job.target }}.zip"
        zip -r $ARCHIVE_PATH out
        
        # Let subsequent steps know where to find the archive
        echo "ARCHIVE_PATH=${ARCHIVE_PATH}" >> $GITHUB_OUTPUT

    - name: Release
      uses: softprops/action-gh-release@v2
      if: github.ref_type == 'tag'
      with:
        files: ${{ steps.bin.outputs.ARCHIVE_PATH }}
        fail_on_unmatched_files: true
        generate_release_notes: true
